In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset.csv", low_memory=False)

#Data Understanding

In [3]:
df.head()

,stn_code,sampling_date,state,location,agency,type,so2,no2,rspm,spm,location_monitoring_station,pm2_5,date
0,150,February - M021990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",4.8,17.4,NaN,NaN,NaN,NaN,2/1/1990
1,151,February - M021990,Andhra Pradesh,Hyderabad,NaN,Industrial Area,3.1,7.0,NaN,NaN,NaN,NaN,2/1/1990
2,152,February - M021990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",6.2,28.5,NaN,NaN,NaN,NaN,2/1/1990
3,150,March - M031990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",6.3,14.7,NaN,NaN,NaN,NaN,3/1/1990
4,151,March - M031990,Andhra Pradesh,Hyderabad,NaN,Industrial Area,4.7,7.5,NaN,NaN,NaN,NaN,3/1/1990

In [4]:
df.tail()

,stn_code,sampling_date,state,location,agency,type,so2,no2,rspm,spm,location_monitoring_station,pm2_5,date
435737,SAMP,24-12-15,West Bengal,ULUBERIA,West Bengal State Pollution Control Board,RIRUO,22.0,50.0,143.0,NaN,"Inside Rampal Industries,ULUBERIA",NaN,12/24/2015
435738,SAMP,29-12-15,West Bengal,ULUBERIA,West Bengal State Pollution Control Board,RIRUO,20.0,46.0,171.0,NaN,"Inside Rampal Industries,ULUBERIA",NaN,12/29/2015
435739,NaN,NaN,andaman-and-nicobar-islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435740,NaN,NaN,Lakshadweep,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435741,NaN,NaN,Tripura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(435742, 13)

In [6]:
df.columns

Index(['stn_code', 'sampling_date', 'state', 'location', 'agency', 'type',
       'so2', 'no2', 'rspm', 'spm', 'location_monitoring_station', 'pm2_5',
       'date'],
      dtype='str')

In [7]:
df.dtypes

stn_code                           str
sampling_date                      str
state                              str
location                           str
agency                             str
type                               str
so2                            float64
no2                            float64
rspm                           float64
spm                            float64
location_monitoring_station        str
pm2_5                          float64
date                               str
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 435742 entries, 0 to 435741
Data columns (total 13 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   stn_code                     291665 non-null  str
 1   sampling_date                435739 non-null  str
 2   state                        435742 non-null  str
 3   location                     435739 non-null  str
 4   agency                       286261 non-null  str
 5   type                         430349 non-null  str
 6   so2                          401096 non-null  float64
 7   no2                          419509 non-null  float64
 8   rspm                         395520 non-null  float64
 9   spm                          198355 non-null  float64
 10  location_monitoring_station  408251 non-null  str
 11  pm2_5                        9314 non-null    float64
 12  date                         435735 non-null  str
dtypes: float64(5), str(8)
memory usage: 43.2 MB

In [9]:
df.describe()

                 so2            no2           rspm            spm        pm2_5
count  401096.000000  419509.000000  395520.000000  198355.000000  9314.000000
mean       10.829414      25.809623     108.832784     220.783480    40.791467
std        11.177187      18.503086      74.872430     151.395457    30.832525
min         0.000000       0.000000       0.000000       0.000000     3.000000
25%         5.000000      14.000000      56.000000     111.000000    24.000000
50%         8.000000      22.000000      90.000000     187.000000    32.000000
75%        13.700000      32.200000     142.000000     296.000000    46.000000
max       909.000000     876.000000    6307.033333    3380.000000   504.000000

In [10]:
df.isnull().sum()

stn_code                       144077
sampling_date                       3
state                               0
location                            3
agency                         149481
type                             5393
so2                             34646
no2                             16233
rspm                            40222
spm                            237387
location_monitoring_station     27491
pm2_5                          426428
date                                7
dtype: int64

In [11]:
(df.isnull().sum() / len(df)) * 100

stn_code                       33.064749
sampling_date                   0.000688
state                           0.000000
location                        0.000688
agency                         34.304933
type                            1.237659
so2                             7.951035
no2                             3.725370
rspm                            9.230692
spm                            54.478797
location_monitoring_station     6.309009
pm2_5                          97.862497
date                            0.001606
dtype: float64

In [12]:
df.duplicated().sum()

np.int64(674)

In [13]:
df.nunique()

stn_code                        745
sampling_date                  5485
state                            37
location                        304
agency                           64
type                             10
so2                            4197
no2                            6864
rspm                           6065
spm                            6668
location_monitoring_station     991
pm2_5                           433
date                           5067
dtype: int64

In [14]:
df["state"].unique()

<StringArray>
[             'Andhra Pradesh',           'Arunachal Pradesh',
                       'Assam',                       'Bihar',
                  'Chandigarh',                'Chhattisgarh',
        'Dadra & Nagar Haveli',                 'Daman & Diu',
                       'Delhi',                         'Goa',
                     'Gujarat',                     'Haryana',
            'Himachal Pradesh',             'Jammu & Kashmir',
                   'Jharkhand',                   'Karnataka',
                      'Kerala',              'Madhya Pradesh',
                 'Maharashtra',                     'Manipur',
                   'Meghalaya',                     'Mizoram',
                    'Nagaland',                      'Odisha',
                  'Puducherry',                      'Punjab',
                   'Rajasthan',                      'Sikkim',
                  'Tamil Nadu',                   'Telangana',
               'Uttar Pradesh',                 'Uttarakhand',
                 'Uttaranchal',                 'West Bengal',
 'andaman-and-nicobar-islands',                 'Lakshadweep',
                     'Tripura']
Length: 37, dtype: str

In [15]:
df["type"].unique()

<StringArray>
['Residential, Rural and other Areas',                    'Industrial Area',
                                  nan,                     'Sensitive Area',
                   'Industrial Areas',             'Residential and others',
                    'Sensitive Areas',                         'Industrial',
                        'Residential',                              'RIRUO',
                          'Sensitive']
Length: 11, dtype: str

##Data Cleaning

In [16]:
df_clean = df.copy()

In [17]:
df_clean.tail()

,stn_code,sampling_date,state,location,agency,type,so2,no2,rspm,spm,location_monitoring_station,pm2_5,date
435737,SAMP,24-12-15,West Bengal,ULUBERIA,West Bengal State Pollution Control Board,RIRUO,22.0,50.0,143.0,NaN,"Inside Rampal Industries,ULUBERIA",NaN,12/24/2015
435738,SAMP,29-12-15,West Bengal,ULUBERIA,West Bengal State Pollution Control Board,RIRUO,20.0,46.0,171.0,NaN,"Inside Rampal Industries,ULUBERIA",NaN,12/29/2015
435739,NaN,NaN,andaman-and-nicobar-islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435740,NaN,NaN,Lakshadweep,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435741,NaN,NaN,Tripura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_clean = df_clean.dropna(how='all')

In [19]:
df_clean.tail()

,stn_code,sampling_date,state,location,agency,type,so2,no2,rspm,spm,location_monitoring_station,pm2_5,date
435737,SAMP,24-12-15,West Bengal,ULUBERIA,West Bengal State Pollution Control Board,RIRUO,22.0,50.0,143.0,NaN,"Inside Rampal Industries,ULUBERIA",NaN,12/24/2015
435738,SAMP,29-12-15,West Bengal,ULUBERIA,West Bengal State Pollution Control Board,RIRUO,20.0,46.0,171.0,NaN,"Inside Rampal Industries,ULUBERIA",NaN,12/29/2015
435739,NaN,NaN,andaman-and-nicobar-islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435740,NaN,NaN,Lakshadweep,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435741,NaN,NaN,Tripura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_clean = df_clean.drop_duplicates()

In [21]:
df_clean.duplicated().sum()

np.int64(0)

In [22]:
df_clean.shape

(435068, 13)

In [23]:
df_clean.isnull().sum()

stn_code                       144077
sampling_date                       3
state                               0
location                            3
agency                         149466
type                             5357
so2                             34632
no2                             16222
rspm                            40035
spm                            236908
location_monitoring_station     27303
pm2_5                          425754
date                                7
dtype: int64

In [24]:
df_clean = df_clean.drop(columns=["agency","pm2_5", "location_monitoring_station"])

In [25]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 435068 entries, 0 to 435741
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   stn_code       290991 non-null  str
 1   sampling_date  435065 non-null  str
 2   state          435068 non-null  str
 3   location       435065 non-null  str
 4   type           429711 non-null  str
 5   so2            400436 non-null  float64
 6   no2            418846 non-null  float64
 7   rspm           395033 non-null  float64
 8   spm            198160 non-null  float64
 9   date           435061 non-null  str
dtypes: float64(4), str(6)
memory usage: 36.5 MB

In [26]:
sorted(df_clean["state"].unique())

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra & Nagar Haveli',
 'Daman & Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Lakshadweep',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'Uttaranchal',
 'West Bengal',
 'andaman-and-nicobar-islands']

In [27]:
df_clean["state"] = df_clean["state"].replace({"Uttaranchal":"Uttarakhand","andaman-and-nicobar-islands":"Andaman and Nicobar Islands"})

In [28]:
sorted(df_clean["state"].unique())

['Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra & Nagar Haveli',
 'Daman & Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Lakshadweep',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [29]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 435068 entries, 0 to 435741
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   stn_code       290991 non-null  str
 1   sampling_date  435065 non-null  str
 2   state          435068 non-null  str
 3   location       435065 non-null  str
 4   type           429711 non-null  str
 5   so2            400436 non-null  float64
 6   no2            418846 non-null  float64
 7   rspm           395033 non-null  float64
 8   spm            198160 non-null  float64
 9   date           435061 non-null  str
dtypes: float64(4), str(6)
memory usage: 36.5 MB

In [30]:
df_clean["sampling_date"].sample(20)

52263           3/7/2009
99743           16-06-14
74937           7/6/2005
66381       January_1995
208914          26-10-07
417010         27/8/2006
396764        30/04/2012
260282          27-08-13
65955     June - M061990
40350           16-09-14
361214          7/7/2014
374828          4/3/2006
245553          13-10-14
410186         11/5/2015
173388          13-08-14
220324         12/9/2010
281034          9/6/2012
72731           29-08-13
203792          21-11-05
371466         10/6/2004
Name: sampling_date, dtype: str

In [31]:
df_clean["date"].sample(20)

173500     7/16/2014
159707    10/14/2008
2311       2/22/2005
240442      4/2/2013
280522     6/18/2012
75631      9/27/2007
46538       4/1/2000
195595    12/17/2015
134945     8/27/2014
120670     4/27/2013
95807       5/3/2011
276276     3/19/2008
199900     7/11/2003
289863     6/24/2006
402074     8/26/2013
362852     3/18/2015
310627     6/24/2013
109927     4/30/2007
208361    11/30/2007
152748      9/1/1990
Name: date, dtype: str

In [32]:
df_clean[["sampling_date", "date"]].isnull().sum()

sampling_date    3
date             7
dtype: int64

In [33]:
df_clean = df_clean.drop(columns=["sampling_date"])

In [34]:
df_clean["date"] = pd.to_datetime(df_clean["date"])

In [35]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 435068 entries, 0 to 435741
Data columns (total 9 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   stn_code  290991 non-null  str
 1   state     435068 non-null  str
 2   location  435065 non-null  str
 3   type      429711 non-null  str
 4   so2       400436 non-null  float64
 5   no2       418846 non-null  float64
 6   rspm      395033 non-null  float64
 7   spm       198160 non-null  float64
 8   date      435061 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(4), str(4)
memory usage: 33.2 MB

In [36]:
df_clean[["so2","no2","rspm","spm"]].isnull().any(axis=1).sum()

np.int64(293157)

In [37]:
df_clean = df_clean.dropna(subset=["so2", "no2", "rspm"])

In [38]:
df_clean.isnull().sum()

stn_code    111829
state            0
location         0
type           200
so2              0
no2              0
rspm             0
spm         222644
date             4
dtype: int64

In [39]:
df_clean = df_clean.drop(columns=["spm"])

In [40]:
df_clean.shape

(364555, 8)

In [41]:
df_clean.isnull().sum()

stn_code    111829
state            0
location         0
type           200
so2              0
no2              0
rspm             0
date             4
dtype: int64

In [42]:
df_clean = df_clean.drop(columns=["stn_code"])

In [43]:
df_clean = df_clean.dropna(subset=["type"])

In [44]:
df_clean = df_clean.dropna(subset=["date"])

In [45]:
df_clean.isnull().sum()

state       0
location    0
type        0
so2         0
no2         0
rspm        0
date        0
dtype: int64

In [46]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 364351 entries, 1036 to 435738
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   state     364351 non-null  str
 1   location  364351 non-null  str
 2   type      364351 non-null  str
 3   so2       364351 non-null  float64
 4   no2       364351 non-null  float64
 5   rspm      364351 non-null  float64
 6   date      364351 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), str(3)
memory usage: 22.2 MB

In [47]:
df_clean.shape

(364351, 7)

In [48]:
df_clean.head()

,state,location,type,so2,no2,rspm,date
1036,Andhra Pradesh,Hyderabad,Industrial Area,12.9,55.8,143.7,2004-02-01
1037,Andhra Pradesh,Hyderabad,Industrial Area,10.4,48.9,124.7,2004-05-01
1038,Andhra Pradesh,Hyderabad,Industrial Area,7.6,50.1,88.0,2004-09-01
1039,Andhra Pradesh,Hyderabad,Industrial Area,7.3,48.5,82.7,2004-12-01
1040,Andhra Pradesh,Hyderabad,Industrial Area,6.8,110.3,122.3,2004-01-16

In [49]:
#df_clean.to_csv("cleaned_dataset.csv", index=False)

In [50]:
so2_breakpoints = [
    (0, 40, 0, 50),
    (41, 80, 51, 100),
    (81, 380, 101, 200),
    (381, 800, 201, 300),
    (801, 1600, 301, 400),
    (1601, 2000, 401, 500)
]

In [51]:
no2_breakpoints = [
    (0, 40, 0, 50),
    (41, 80, 51, 100),
    (81, 180, 101, 200),
    (181, 280, 201, 300),
    (281, 400, 301, 400),
    (401, 1000, 401, 500)
]

In [52]:
rspm_breakpoints = [
    (0, 50, 0, 50),
    (51, 100, 51, 100),
    (101, 250, 101, 200),
    (251, 350, 201, 300),
    (351, 430, 301, 400),
    (431, 600, 401, 500)
]

In [53]:
def calculate_sub_index(concentration, breakpoints):
    """
    Calculate AQI sub-index for a pollutant concentration
    using CPCB breakpoint tables.
    """

    for blo, bhi, ilo, ihi in breakpoints:

        if blo <= concentration <= bhi:

            sub_index = (
                ((ihi - ilo) / (bhi - blo))
                * (concentration - blo)
                + ilo
            )

            return round(sub_index)

    return None

In [54]:
print(calculate_sub_index(20, so2_breakpoints))

25

In [55]:
df_clean["so2_sub"] = df_clean["so2"].apply(
    lambda x: calculate_sub_index(x, so2_breakpoints)
)

df_clean["no2_sub"] = df_clean["no2"].apply(
    lambda x: calculate_sub_index(x, no2_breakpoints)
)

df_clean["rspm_sub"] = df_clean["rspm"].apply(
    lambda x: calculate_sub_index(x, rspm_breakpoints)
)

In [56]:
df_clean.head()

,state,location,type,so2,no2,rspm,date,so2_sub,no2_sub,rspm_sub
1036,Andhra Pradesh,Hyderabad,Industrial Area,12.9,55.8,143.7,2004-02-01,16.0,70.0,129.0
1037,Andhra Pradesh,Hyderabad,Industrial Area,10.4,48.9,124.7,2004-05-01,13.0,61.0,117.0
1038,Andhra Pradesh,Hyderabad,Industrial Area,7.6,50.1,88.0,2004-09-01,10.0,62.0,88.0
1039,Andhra Pradesh,Hyderabad,Industrial Area,7.3,48.5,82.7,2004-12-01,9.0,60.0,83.0
1040,Andhra Pradesh,Hyderabad,Industrial Area,6.8,110.3,122.3,2004-01-16,8.0,130.0,115.0

In [57]:
df_clean["AQI"] = df_clean[
    ["so2_sub", "no2_sub", "rspm_sub"]
].max(axis=1)

In [58]:
df_clean.head()

,state,location,type,so2,no2,rspm,date,so2_sub,no2_sub,rspm_sub,AQI
1036,Andhra Pradesh,Hyderabad,Industrial Area,12.9,55.8,143.7,2004-02-01,16.0,70.0,129.0,129.0
1037,Andhra Pradesh,Hyderabad,Industrial Area,10.4,48.9,124.7,2004-05-01,13.0,61.0,117.0,117.0
1038,Andhra Pradesh,Hyderabad,Industrial Area,7.6,50.1,88.0,2004-09-01,10.0,62.0,88.0,88.0
1039,Andhra Pradesh,Hyderabad,Industrial Area,7.3,48.5,82.7,2004-12-01,9.0,60.0,83.0,83.0
1040,Andhra Pradesh,Hyderabad,Industrial Area,6.8,110.3,122.3,2004-01-16,8.0,130.0,115.0,130.0

In [59]:
def get_aqi_category(aqi):
    if aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Satisfactory"
    elif aqi <= 200:
        return "Moderate"
    elif aqi <= 300:
        return "Poor"
    elif aqi <= 400:
        return "Very Poor"
    else:
        return "Severe"

In [60]:
df_clean["AQI_Category"] = df_clean["AQI"].apply(get_aqi_category)

In [61]:
df_clean.head()

,state,location,type,so2,no2,rspm,date,so2_sub,no2_sub,rspm_sub,AQI,AQI_Category
1036,Andhra Pradesh,Hyderabad,Industrial Area,12.9,55.8,143.7,2004-02-01,16.0,70.0,129.0,129.0,Moderate
1037,Andhra Pradesh,Hyderabad,Industrial Area,10.4,48.9,124.7,2004-05-01,13.0,61.0,117.0,117.0,Moderate
1038,Andhra Pradesh,Hyderabad,Industrial Area,7.6,50.1,88.0,2004-09-01,10.0,62.0,88.0,88.0,Satisfactory
1039,Andhra Pradesh,Hyderabad,Industrial Area,7.3,48.5,82.7,2004-12-01,9.0,60.0,83.0,83.0,Satisfactory
1040,Andhra Pradesh,Hyderabad,Industrial Area,6.8,110.3,122.3,2004-01-16,8.0,130.0,115.0,130.0,Moderate

In [62]:
df_clean["AQI_Category"].value_counts()

AQI_Category
Moderate        143923
Satisfactory    135873
Good             66349
Poor             14094
Very Poor         2786
Severe            1326
Name: count, dtype: int64

# Machine Learning

In [63]:
X = df_clean[["so2", "no2", "rspm"]]

y = df_clean["AQI"]

In [64]:
print(X.head())

       so2    no2   rspm
1036  12.9   55.8  143.7
1037  10.4   48.9  124.7
1038   7.6   50.1   88.0
1039   7.3   48.5   82.7
1040   6.8  110.3  122.3

In [65]:
print(y.head())

1036    129.0
1037    117.0
1038     88.0
1039     83.0
1040    130.0
Name: AQI, dtype: float64

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [67]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred[:10])

[114.70829004  57.46830121 104.85006969  61.89918196  87.51964763
  40.3746887  239.578626    74.91386718  68.82692107  98.30958328]

In [68]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = mse ** 0.5

r2 = r2_score(y_test, y_pred)
print("Mean Absolute Error (MAE):", mae)
print("Root Mean Squared Error (RMSE):", rmse)
print("R² Score:", r2)

Mean Absolute Error (MAE): 5.846129800977274
Root Mean Squared Error (RMSE): 14.603952405043886
R² Score: 0.9381466548093246

In [69]:
so2 = float(input("Enter SO₂ value: "))
no2 = float(input("Enter NO₂ value: "))
rspm = float(input("Enter RSPM value: "))

user_data = [[so2, no2, rspm]]

predicted_aqi = model.predict(user_data)[0]

print(f"\nPredicted AQI: {predicted_aqi:.2f}")

category = get_aqi_category(predicted_aqi)

print("AQI Category:", category)

Enter SO₂ value:  10
Enter NO₂ value:  10
Enter RSPM value:  10

Predicted AQI: 25.23
AQI Category: Good

C:\Users\ummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [70]:
import joblib

# Save the trained Linear Regression model
joblib.dump(model, "model.pkl")

print("Model saved successfully!")

Model saved successfully!